site_name: Documentation
site_dir : ../../dist/assets/help/howto
#site_dir : ../../dist/assets/help/howto
repo_url: http:github.com/freegroup

pages:
 - Home : index.md
 - Getting Startet: startet/index.md
 - Platform : platforms/index.md

theme: material

extra_css: [extra.css]
