site_name: Brainbox Getting Started Guide
site_dir : ../../dist/assets/help/howto
repo_url: https://github.com/freegroup/draw2d_js.app.brainbox
edit_uri: blob/dev/docs/

pages:
 - About : index.md
 - Getting Startet: startet/index.md
 - Platform : platforms/index.md

theme: material

extra_css: [extra.css]
