site_name: Documentation
site_dir : ../../dist/assets/help/howto
#site_dir : ../../dist/assets/help/howto

pages:
 - Home : index.md
 - Platform : platforms/index.md

theme: material

extra_css: [extra.css]